# -*- coding: utf-8 -*-
"""Regex.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w_eu4YNyTjDeIGwbiAG9LHGvx7sbUA1L
"""

import regex as re

pattern ="25"
text = "sunil 's birthday is on 25-11-2026"

match = re.search(pattern,text)
print(match)
print(type(match))

pattern="627"
text="my registration no. is 24UG010627"

match=re.search(pattern,text)
print(match)

string="hello 31 hi 56.Sunil 131"
pattern="\d+"

result=re.findall(pattern,string)
print(result)

string="hello 31 hi 56.Sunil 131"
pattern="\d+"

result=re.finditer(pattern,string)
print(result)

pattern ="Sunil"
text = "sunil 's birthday is on 25-11-2026"

match = re.search(pattern,text,re.IGNORECASE)
print(match)
print(type(match))